# Generated by Django 5.2.9 on 2026-01-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this document is currently active'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes or rejection reason', null=True),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
