# Generated by Django 5.0.14 on 2026-04-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerdocument_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
