# Generated by Django 5.2.7 on 2025-10-09 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mpesa_reference', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='policies.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commission_count', models.PositiveIntegerField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.agency')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(choices=[('PAYOUT', 'Direct Payout'), ('UPLINE', 'Upline Payout'), ('BONUS', 'Bonus'), ('CLAWBACK', 'Clawback')], max_length=20)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('BATCHED', 'Batched for Payout'), ('PAID', 'Paid'), ('REVERSED', 'Reversed')], db_index=True, default='PENDING_APPROVAL', max_length=20)),
                ('applied_rule_details', models.JSONField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='accounts.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='accounts.agencybranch')),
                ('payout_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.payoutbatch')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='policies.policy')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_approve_commission', 'Can approve staff commission')],
            },
        ),
        migrations.CreateModel(
            name='ProviderCommissionStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(choices=[('NEW_BUSINESS', 'New Business'), ('RENEWAL', 'Renewal')], max_length=20)),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_commission_structures', to='accounts.agency')),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.policytype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_structures', to='policies.insuranceprovider')),
            ],
            options={
                'unique_together': {('agency', 'provider', 'policy_type', 'commission_type')},
            },
        ),
        migrations.CreateModel(
            name='StaffCommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_basis', models.CharField(choices=[('AGENCY_COMMISSION', 'Agency Commission'), ('TOTAL_PREMIUM', 'Total Premium')], max_length=20)),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_commission_rules', to='accounts.agency')),
                ('policy_type', models.ForeignKey(blank=True, help_text='Optional: Make this rule specific to a policy type', null=True, on_delete=django.db.models.deletion.PROTECT, to='policies.policytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('agency', 'user', 'policy_type')},
            },
        ),
    ]
