# Generated by Django 5.2.7 on 2025-10-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('policies', '0002_rename_premium_amount_policy_total_premium_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcommission',
            name='installment',
            field=models.ForeignKey(blank=True, help_text='The specific installment this commission was generated from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='policies.policyinstallment'),
        ),
        migrations.AlterField(
            model_name='staffcommission',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='policies.policy'),
        ),
    ]
