# Generated by Django 5.0.14 on 2026-01-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_staffcommissionrule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcommissionrule',
            name='monthly_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The monthly production amount (based on payout_basis) that must be reached before commission is earned.', max_digits=12),
        ),
    ]
