# Generated by Django 5.0.14 on 2026-01-07 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
        ('communications', '0001_initial'),
        ('customers', '0002_customerdocument_document_number_and_more'),
        ('policies', '0004_remove_policy_total_premium_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('POLICY_EXPIRING', 'Policy Expiring'), ('AGENT_DAILY_SUMMARY', 'Agent Daily Summary'), ('AGENT_URGENT_ALERT', 'Agent Urgent Alert'), ('AGENT_RENEWAL_OPP', 'Agent Renewal Opportunities')], db_index=True, max_length=50)),
                ('name', models.CharField(help_text='Descriptive name for this template', max_length=255)),
                ('sms_template', models.TextField(blank=True, help_text='SMS message template with {{placeholders}}. Keep under 160 characters.')),
                ('email_subject_template', models.CharField(blank=True, help_text='Email subject line with {{placeholders}}', max_length=255)),
                ('email_body_template', models.TextField(blank=True, help_text='Email body template (plain text) with {{placeholders}}')),
                ('is_active', models.BooleanField(default=True, help_text="If False, this template won't be used")),
            ],
            options={
                'verbose_name': 'Reminder Template',
                'verbose_name_plural': 'Reminder Templates',
                'ordering': ['reminder_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('POLICY_EXPIRING', 'Policy Expiring'), ('AGENT_DAILY_SUMMARY', 'Agent Daily Summary'), ('AGENT_URGENT_ALERT', 'Agent Urgent Alert'), ('AGENT_RENEWAL_OPP', 'Agent Renewal Opportunities')], db_index=True, max_length=50)),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent')], max_length=20)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('sms_content', models.TextField(blank=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], db_index=True, default='QUEUED', max_length=20)),
                ('delivery_status', models.JSONField(blank=True, default=dict, help_text="Provider response data (Africa's Talking, SMTP, etc.)")),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='customers.customer')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_logs', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Reminder Log',
                'verbose_name_plural': 'Reminder Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reminder_type', 'created_at'], name='communicati_reminde_35657b_idx'), models.Index(fields=['customer', 'reminder_type'], name='communicati_custome_7eb301_idx'), models.Index(fields=['agent', 'reminder_type'], name='communicati_agent_i_f897f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('POLICY_EXPIRING', 'Policy Expiring'), ('AGENT_DAILY_SUMMARY', 'Agent Daily Summary'), ('AGENT_URGENT_ALERT', 'Agent Urgent Alert'), ('AGENT_RENEWAL_OPP', 'Agent Renewal Opportunities')], db_index=True, max_length=50)),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable this reminder type for this agency')),
                ('days_before', models.IntegerField(blank=True, help_text='For expiry/due reminders: how many days before to send', null=True)),
                ('time_of_day', models.TimeField(blank=True, help_text='Preferred time to send this reminder', null=True)),
                ('channels_enabled', models.JSONField(default=dict, help_text='{"sms": true, "email": true}')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='accounts.agency')),
            ],
            options={
                'verbose_name': 'Reminder Setting',
                'verbose_name_plural': 'Reminder Settings',
                'ordering': ['agency', 'reminder_type'],
                'unique_together': {('agency', 'reminder_type', 'days_before')},
            },
        ),
    ]
