# Generated by Django 5.0.14 on 2026-01-07 07:29

from django.db import migrations

def seed_templates(apps, schema_editor):
    ReminderTemplate = apps.get_model('communications', 'ReminderTemplate')
    
    templates = [
        # CUSTOMER TEMPLATES
        {
            'reminder_type': 'PAYMENT_DUE',
            'name': 'Customer Payment Due Reminder',
            'sms_template': 'Hello {{customer_name}}, a payment for your policy {{policy_number}} is due on {{next_due_date}}. Amount: KES {{installment_amount}}.',
            'email_subject_template': 'Payment Reminder: Policy {{policy_number}}',
            'email_body_template': 'emails/customer_payment_due.html', # Path to file for render_to_string
            'is_active': True,
        },
        {
            'reminder_type': 'PAYMENT_OVERDUE',
            'name': 'Customer Payment Overdue Alert',
            'sms_template': 'Hello {{customer_name}}, your payment for policy {{policy_number}} is {{days_overdue}} days OVERDUE. Please pay KES {{installment_amount}} immediately.',
            'email_subject_template': 'URGENT: Overdue Payment for Policy {{policy_number}}',
            'email_body_template': 'emails/customer_payment_overdue.html',
            'is_active': True,
        },
        {
            'reminder_type': 'POLICY_EXPIRING',
            'name': 'Customer Policy Expiry Reminder',
            'sms_template': 'Hello {{customer_name}}, your policy {{policy_number}} expires in {{days_until_expiry}} days ({{policy_end_date}}). Contact us to renew.',
            'email_subject_template': 'Policy Expiration Notice: {{policy_number}}',
            'email_body_template': 'emails/customer_policy_expiring.html',
            'is_active': True,
        },
        
        # AGENT TEMPLATES
        {
            'reminder_type': 'AGENT_DAILY_SUMMARY',
            'name': 'Agent Portfolio Daily Summary',
            'sms_template': '', # No SMS for summary
            'email_subject_template': 'Your Daily Portfolio Summary - {{summary_date}}',
            'email_body_template': 'emails/agent_daily_summary.html',
            'is_active': True,
        },
        {
            'reminder_type': 'AGENT_URGENT_ALERT',
            'name': 'Agent Urgent Policy Alert',
            'sms_template': 'URGENT: {{at_risk_count}} policies in your portfolio are now AT RISK due to missing payments. Policies: {{policy_numbers}}.',
            'email_subject_template': 'URGENT ALERT: Policies At Risk',
            'email_body_template': 'emails/agent_urgent_alert.html',
            'is_active': True,
        },
        {
            'reminder_type': 'AGENT_RENEWAL_OPP',
            'name': 'Agent Renewal Opportunities Report',
            'sms_template': '', # No SMS for report
            'email_subject_template': 'Upcoming Renewal Opportunities (30-60 Days)',
            'email_body_template': 'emails/agent_renewal_opportunities.html',
            'is_active': True,
        },
    ]
    
    for t_data in templates:
        ReminderTemplate.objects.get_or_create(
            reminder_type=t_data['reminder_type'],
            defaults={
                'name': t_data['name'],
                'sms_template': t_data['sms_template'],
                'email_subject_template': t_data['email_subject_template'],
                'email_body_template': t_data['email_body_template'],
                'is_active': t_data['is_active'],
            }
        )

def remove_templates(apps, schema_editor):
    ReminderTemplate = apps.get_model('communications', 'ReminderTemplate')
    ReminderTemplate.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_remindertemplate_reminderlog_remindersettings'),
    ]

    operations = [
        migrations.RunPython(seed_templates, remove_templates),
    ]
