# Generated by Django 5.2.9 on 2026-01-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_seed_reminder_templates'),
    ]

    operations = [
    ]
