from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    CustomerPaymentViewSet, ProviderCommissionStructureViewSet, StaffCommissionRuleViewSet,
    StaffCommissionViewSet, PayoutBatchViewSet
)

# Create a router to automatically generate the URLs for our ViewSets.
router = DefaultRouter()

# Register each ViewSet with a descriptive URL endpoint.
router.register(r'customer-payments', CustomerPaymentViewSet, basename='customer-payment')
router.register(r'provider-commission-structures', ProviderCommissionStructureViewSet, basename='provider-commission-structure')
router.register(r'staff-commission-rules', StaffCommissionRuleViewSet, basename='staff-commission-rule')
router.register(r'staff-commissions', StaffCommissionViewSet, basename='staff-commission')
router.register(r'payout-batches', PayoutBatchViewSet, basename='payout-batch')

# The urlpatterns are automatically generated by the router.
urlpatterns = [
    path('', include(router.urls)),
]