# Generated by Django 5.2.7 on 2025-10-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False},
        ),
    ]
