# File: insurance_agency_project/settings.py

"""
Django settings for insurance_agency_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from celery import Celery

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-m-aiipr$+8#n5@gakvm!0vydl(teiy2f2)z^3bg%=g=uew8cp4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CORS_ALLOW_CREDENTIALS = True

ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost",
    "http://localhost:3001",
    "http://localhost:5173",
    "http://insmanag_frontend:3000",
    "http://192.168.100.151",
]


AFRICASTALKING_USERNAME = os.environ.get('AFRICASTALKING_USERNAME', 'sandbox') # Default to sandbox
AFRICASTALKING_API_KEY = os.environ.get('AFRICASTALKING_API_KEY')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'django_filters',

    # Local apps
    'apps.accounts',
    'apps.auditing',
    'apps.communications',
    'apps.commissions',
    'apps.core',
    'apps.customers',
    'apps.policies',
    'apps.analytics',
    'apps.claims',
    'apps.reportings',
    'apps.finances',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'

ROOT_URLCONF = 'insurance_agency_project.urls'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "SIGNING_KEY": SECRET_KEY,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Insurance Agency API",
    "DESCRIPTION": "API for managing agencies, branches, and users with role-based access control.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'insurance_agency_project.wsgi.application'

# <-- ADD THIS LINE
# Tell Django that it is being served from a sub-path.
# All generated URLs (redirects, etc.) will now be prefixed with /api.
FORCE_SCRIPT_NAME = '/api'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('DB_PORT', 5432),
    }
}

# Redis & Celery
CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', 6379)}/0"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# --- ADD THIS NEW SETTING ---
# Explicitly tell Celery where to find our tasks.
CELERY_IMPORTS = (
    'apps.policies.tasks',
    'apps.auditing.tasks',
    'apps.commissions.tasks',
    'apps.communications.reminder_tasks',
)
# --- CORRECTED CELERY BEAT SCHEDULE ---
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Existing tasks
    'send-daily-policy-expiry-reminders': {
        'task': 'apps.policies.tasks.send_daily_policy_expiry_reminders',
        'schedule': crontab(hour=10, minute=0), # Adjusted to not overlap
    },
    'update-expired-policies-status-frequently': {
        'task': 'apps.policies.tasks.update_expired_policies_status',
        'schedule': crontab(hour='*/2', minute=5),
    },
    
    # --- NEW CUSTOMER REMINDER TASKS ---
    'customer-payment-reminders': {
        'task': 'apps.communications.tasks.send_customer_payment_reminders',
        'schedule': crontab(hour=9, minute=0),
    },
    'customer-overdue-reminders': {
        'task': 'apps.communications.tasks.send_customer_overdue_reminders',
        'schedule': crontab(hour=10, minute=0),
    },
    'customer-expiry-reminders-multi-stage': {
        'task': 'apps.communications.tasks.send_customer_policy_expiry_reminders',
        'schedule': crontab(hour=9, minute=30),
    },

    # --- NEW AGENT REMINDER TASKS ---
    'agent-daily-summary': {
        'task': 'apps.communications.tasks.send_agent_daily_summary',
        'schedule': crontab(hour=8, minute=0, day_of_week='1-5'),
    },
    'agent-urgent-alerts': {
        'task': 'apps.communications.tasks.send_agent_urgent_alerts',
        'schedule': crontab(hour='*/6', minute=0),
    },
    'agent-renewal-opportunities': {
        'task': 'apps.communications.tasks.send_agent_renewal_opportunities',
        'schedule': crontab(hour=9, minute=0, day_of_week='1'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Optional but good practice: Tell Django where to find your project's own static files.
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Report Settings
REPORTS_DIR = BASE_DIR / 'reports'
REPORTS_TEMP_DIR = BASE_DIR / 'reports' / 'temp'

# Create directories
REPORTS_DIR.mkdir(exist_ok=True)
REPORTS_TEMP_DIR.mkdir(exist_ok=True)

# Limits
REPORT_MAX_RECORDS_PDF = 500
REPORT_MAX_RECORDS_EXCEL = 10000
REPORT_MAX_RECORDS_CSV = 100000

# Email Configuration (Placeholders - configured via .env)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Insurance Agency <noreply@example.com>')