# Generated by Django 5.2.9 on 2026-01-01 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_types', to='accounts.agency')),
            ],
            options={
                'unique_together': {('agency', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContractDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE_OF_BASE', 'Percentage of Base Salary')], default='FIXED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount value or Percentage (e.g. 5.0 for 5%)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='finances.staffcontract')),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.deductiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='deduction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.deductiontype'),
        ),
    ]
