# Generated by Django 5.2.9 on 2026-01-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_deductiontype_contractdeduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('ONE_TIME', 'One Time'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], default='ONE_TIME', max_length=20),
        ),
    ]
