# Generated by Django 5.2.7 on 2025-10-09 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('date_of_loss', models.DateField()),
                ('loss_description', models.TextField()),
                ('status', models.CharField(choices=[('FNOL', 'First Notice of Loss'), ('UNDER_REVIEW', 'Under Review'), ('AWAITING_DOCS', 'Awaiting Documents'), ('APPROVED', 'Approved'), ('SETTLED', 'Settled / Paid'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], db_index=True, default='FNOL', max_length=30)),
                ('estimated_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='accounts.agency')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='accounts.agencybranch')),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='customers.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_settle_claim', 'Can settle approved claims')],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(help_text='e.g., Police Report, Photo of Damage', max_length=100)),
                ('file', models.FileField(upload_to='claim_documents/%Y/%m/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
