# Generated by Django 5.2.7 on 2025-10-09 12:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name or trading name', max_length=100)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternative_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('fax_number', models.CharField(blank=True, max_length=17)),
                ('website', models.URLField(blank=True)),
                ('physical_address', models.TextField(blank=True, help_text='Street address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('postal_address', models.CharField(blank=True, help_text='P.O. Box address', max_length=255)),
                ('contact_person_name', models.CharField(blank=True, max_length=255)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('contact_person_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('claims_email', models.EmailField(blank=True, help_text='Dedicated claims email', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('claims_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Default commission percentage', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this provider')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='provider_logos/')),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('requires_vehicle_reg', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_types', to='accounts.agency')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('agency', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID_PENDING_ACTIVATION', 'Paid - Pending Activation'), ('ACTIVE', 'Active'), ('LAPSED', 'Lapsed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='AWAITING_PAYMENT', max_length=30)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='accounts.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_policies', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='accounts.agencybranch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='customers.customer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='policies.insuranceprovider')),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='policies.policytype')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
