# Generated by Django 5.2.7 on 2025-10-09 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='premium_amount',
            new_name='total_premium_amount',
        ),
        migrations.AddField(
            model_name='policy',
            name='is_installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID_PENDING_ACTIVATION', 'Paid - Pending Activation'), ('ACTIVE', 'Active'), ('ACTIVE_INSTALLMENT', 'Active (Installment)'), ('LAPSED', 'Lapsed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='AWAITING_PAYMENT', max_length=30),
        ),
        migrations.CreateModel(
            name='PolicyInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Policy Installment',
                'verbose_name_plural': 'Policy Installments',
                'ordering': ['due_date'],
            },
        ),
    ]
