# Generated by Django 5.2.8 on 2025-11-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_rename_premium_amount_policy_total_premium_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='additional_details',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible field for policy-specific data (e.g., beneficiaries, property address).'),
        ),
        migrations.AddField(
            model_name='policy',
            name='deductible',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The deductible or excess amount to be paid by the customer on a claim.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='The date the next payment is due for a recurring policy.', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUALLY', 'Semi-Annually'), ('ANNUALLY', 'Annually')], help_text='The payment frequency for recurring fee policies.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The total premium for premium-based policies, or the recurring fee amount for recurring policies.', max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='sum_insured',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total amount of coverage or sum assured (e.g., for life, property).', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='policytype',
            name='payment_structure',
            field=models.CharField(choices=[('PREMIUM_BASED', 'Premium Based'), ('RECURRING_FEE', 'Recurring Fee')], default='PREMIUM_BASED', help_text='Defines if this is a standard premium policy or a recurring payment policy.', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='is_installment',
            field=models.BooleanField(default=False, help_text='True if a premium-based policy is paid in installments.'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID_PENDING_ACTIVATION', 'Paid - Pending Activation'), ('ACTIVE', 'Active'), ('ACTIVE_INSTALLMENT', 'Active (Installment)'), ('AT_RISK_MISSING_PAYMENT', 'At Risk (Missing Payment)'), ('ACTIVE_RECURRING', 'Active (Recurring)'), ('LAPSED', 'Lapsed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='AWAITING_PAYMENT', max_length=30),
        ),
    ]