# Generated by Django 5.2.8 on 2025-11-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_remove_policy_total_premium_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='total_premium_amount',
        ),
    ]
