# Generated by Django 5.2.12 on 2026-04-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_remove_policy_total_premium_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='insurance_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='policy_certificates/'),
        ),
    ]
