# Generated by Django 5.2.7 on 2025-10-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsDashboard',
        ),
    ]
