# Generated by Django 5.2.9 on 2026-01-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
        ('auditing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='agency_name',
            field=models.CharField(blank=True, help_text='Cached agency name for reference', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.agency'),
        ),
    ]
